MODEL_NAME = "unsloth/Qwen3-VL-8B-Instruct-unsloth-bnb-4bit"
MAX_SEQ_LEN = 16384
LORA_RANK = 16

DATASET = "BUAADreamer/clevr_count_70k"
DATASET_SIZE = 5000

REASONING_START = "<REASONING>"
REASONING_END = "</REASONING>"
SOLUTION_START = "<SOLUTION>"
SOLUTION_END = "</SOLUTION>"
