MODEL_NAME = "unsloth/Qwen3-VL-8B-Instruct-unsloth-bnb-4bit"
MAX_SEQ_LEN = 16384
LORA_RANK = 16

DATASET = "HuggingFaceM4/ChartQA"
DATASET_SIZE = 500

REASONING_START = "<REASONING>"
REASONING_END = "</REASONING>"
SOLUTION_START = "<SOLUTION>"
SOLUTION_END = "</SOLUTION>"
